defmodule AshTest.Repo.Migrations.Update do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :name, :text, null: false
      add :bio, :text
      add :sex, :text, default: "non_binary"
      add :account_id, :uuid
    end

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:tickets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :subject, :text, null: false
      add :status, :text, null: false, default: "open"
      add :representative_id, :uuid
    end

    create table(:representatives, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
    end

    alter table(:tickets) do
      modify :representative_id,
             references(:representatives,
               column: :id,
               prefix: "public",
               name: "tickets_representative_id_fkey",
               type: :uuid
             )
    end

    alter table(:representatives) do
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :name, :text
    end

    create table(:accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
    end

    alter table(:users) do
      modify :account_id,
             references(:accounts,
               column: :id,
               prefix: "public",
               name: "users_account_id_fkey",
               type: :uuid
             )
    end

    alter table(:accounts) do
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :username, :text, null: false
      add :email, :citext, null: false
      add :hashed_password, :text, null: false
    end

    create unique_index(:accounts, [:email], name: "accounts_unique_email_index")

    create unique_index(:accounts, [:username], name: "accounts_unique_username_index")
  end

  def down do
    drop_if_exists unique_index(:accounts, [:username], name: "accounts_unique_username_index")

    drop_if_exists unique_index(:accounts, [:email], name: "accounts_unique_email_index")

    alter table(:accounts) do
      remove :hashed_password
      remove :email
      remove :username
      remove :updated_at
      remove :created_at
    end

    drop constraint(:users, "users_account_id_fkey")

    alter table(:users) do
      modify :account_id, :uuid
    end

    drop table(:accounts)

    alter table(:representatives) do
      remove :name
      remove :updated_at
      remove :created_at
    end

    drop constraint(:tickets, "tickets_representative_id_fkey")

    alter table(:tickets) do
      modify :representative_id, :uuid
    end

    drop table(:representatives)

    drop table(:tickets)

    drop table(:tokens)

    drop table(:users)
  end
end