defmodule AshTest.Repo.Migrations.AddOneToManyRelationshipBetweenAccountsAndTicket do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      add :account_id,
          references(:accounts,
            column: :id,
            name: "tickets_account_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:tickets, "tickets_account_id_fkey")

    alter table(:tickets) do
      remove :account_id
    end
  end
end